from typing import Optional, List
from fastapi import APIRouter, Depends, Form, Response
from sqlalchemy.orm import Session
from pydantic import BaseModel
from datetime import datetime
from app.core.database import get_db
from app.api.deps import get_current_active_manager
from app.models.employee import Employee
from app.models.whatsapp_log import WhatsAppLog
from app.services.whatsapp_service import process_whatsapp_message

router = APIRouter()

class WhatsAppLogResponse(BaseModel):
    id: str
    phone_number: str
    message_body: str
    direction: str
    twilio_message_sid: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True

@router.get("/logs", response_model=List[WhatsAppLogResponse])
def list_whatsapp_logs(
    limit: int = 200,
    current_user: Employee = Depends(get_current_active_manager),
    db: Session = Depends(get_db)
):
    logs = db.query(WhatsAppLog).filter(
        WhatsAppLog.company_id == current_user.company_id
    ).order_by(WhatsAppLog.created_at.desc()).limit(limit).all()
    return logs

@router.post("/webhook")
def whatsapp_webhook(
    From: str = Form(...),
    Body: str = Form(""),
    MessageSid: str = Form(None),
    Latitude: Optional[float] = Form(None),
    Longitude: Optional[float] = Form(None),
    db: Session = Depends(get_db)
):
    """
    Webhook target for Twilio. Processes urlencoded POST payloads containing:
    - From: The sender's phone number, e.g. whatsapp:+34600000000
    - Body: Message text command
    - MessageSid: Unique message identifier generated by Twilio
    - Latitude: Optional latitude if location is shared
    - Longitude: Optional longitude if location is shared
    
    Returns a standard TwiML XML response text.
    """
    twiml_response = process_whatsapp_message(
        db, 
        from_phone=From, 
        body=Body, 
        message_sid=MessageSid,
        latitude=Latitude,
        longitude=Longitude
    )
    return Response(content=twiml_response, media_type="text/xml")
