from typing import Optional
from fastapi import APIRouter, Depends, Form, Response
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.services.whatsapp_service import process_whatsapp_message

router = APIRouter()

@router.post("/webhook")
def whatsapp_webhook(
    From: str = Form(...),
    Body: str = Form(""),
    MessageSid: str = Form(None),
    Latitude: Optional[float] = Form(None),
    Longitude: Optional[float] = Form(None),
    db: Session = Depends(get_db)
):
    """
    Webhook target for Twilio. Processes urlencoded POST payloads containing:
    - From: The sender's phone number, e.g. whatsapp:+34600000000
    - Body: Message text command
    - MessageSid: Unique message identifier generated by Twilio
    - Latitude: Optional latitude if location is shared
    - Longitude: Optional longitude if location is shared
    
    Returns a standard TwiML XML response text.
    """
    twiml_response = process_whatsapp_message(
        db, 
        from_phone=From, 
        body=Body, 
        message_sid=MessageSid,
        latitude=Latitude,
        longitude=Longitude
    )
    return Response(content=twiml_response, media_type="text/xml")
